apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.identity.config.name }}
  labels:
    release: {{ .Release.Name }}
    {{- with .Values.identity.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  JWT_SECRET: {{ .Values.jwtSecret }} #Used for creating a JWT. Can be anything
  APP_NAME: {{ .Values.identity.config.appName }}
  ENABLE_SHELL_INJECTION: {{ .Values.enableShellInjection | quote }}
  ENABLE_LOG4J: {{ .Values.enableLog4j | quote }}
  DB_HOST: {{ .Values.postgresdb.service.name }}
  DB_DRIVER: {{ .Values.identity.config.postgresDbDriver }}
  DB_USER: {{ .Values.postgresdb.config.postgresUser }}
  DB_PASSWORD: {{ .Values.postgresdb.config.postgresPassword }}
  DB_NAME: {{ .Values.postgresdb.config.postgresDbName }}
  DB_PORT: {{ .Values.postgresdb.port | quote }}
  MAILHOG_HOST: {{ .Values.mailhog.smtpService.name }}
  MAILHOG_PORT: {{ .Values.mailhog.smtpPort | quote }}
  MAILHOG_DOMAIN: {{ .Values.identity.config.mailhogDomain }}
  SMTP_HOST: {{ .Values.identity.config.smtpHost}}
  SMTP_PORT: {{ .Values.identity.config.smtpPort | quote }}
  SMTP_EMAIL: {{ .Values.identity.config.smtpEmail }}
  SMTP_PASS: {{ .Values.identity.config.smtpPass }}
  SMTP_FROM: {{ .Values.identity.config.smtpFrom }}
  SMTP_AUTH: {{ .Values.identity.config.smtpAuth | quote }}
  JWT_EXPIRATION: {{ .Values.jwtExpiration | quote }}
  SMTP_STARTTLS: {{ .Values.identity.config.smtpStartTLS | quote }}
  SERVER_PORT: {{ .Values.identity.port | quote }}
  API_GATEWAY_URL: {{ if .Values.apiGatewayServiceInstall }}"https://{{ .Values.apiGatewayService.service.name }}"{{ else }}{{ .Values.apiGatewayServiceUrl }}{{ end }}
  TLS_ENABLED: {{ .Values.tlsEnabled | quote }}
  TLS_KEYSTORE_TYPE: {{ .Values.identity.config.keyStoreType }}
  TLS_KEYSTORE: {{ .Values.identity.config.keyStore }}
  TLS_KEYSTORE_PASSWORD: {{ .Values.identity.config.keyStorePassword }}
  TLS_KEY_PASSWORD: {{ .Values.identity.config.keyPassword }}
  TLS_KEY_ALIAS: {{ .Values.identity.config.keyAlias }}
