apiVersion: v1
kind: ConfigMap
metadata:
  name: crapi-web-configmap
  labels:
    app: crapi-web
data: 
  COMMUNITY_SERVICE: crapi-community:8087
  IDENTITY_SERVICE: crapi-identity:8080
  WORKSHOP_SERVICE: crapi-workshop:8000
