apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresdb.name }}
  labels:
    release: {{ .Release.Name }}
    {{- with .Values.postgresdb.statefulsetLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ .Values.postgresdb.service.name }}
  replicas: {{ .Values.postgresdb.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.postgresdb.statefulsetSelectorMatchLabels | nindent 6 }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        {{- toYaml .Values.postgresdb.podLabels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.postgresdb.name }}
          image: {{ .Values.postgresdb.image }}:{{ .Values.postgresdb.version }}
          imagePullPolicy: {{ .Values.postgresdb.imagePullPolicy }}
          args: ["-c", "max_connections=500"]
          ports:
            - containerPort: {{ .Values.postgresdb.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.postgresdb.config.name }}

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
              subPath: postgres
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.postgresdb.pvc.name }}
