apiVersion: apps/v1
kind: Deployment
metadata:
  name: crapi-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crapi-identity
  template:
    metadata:
      labels:
        app: crapi-identity
    spec:
      initContainers:
        - name: wait-for-postgres
          image: groundnuty/k8s-wait-for:v1.3
          imagePullPolicy: Always
          args:
            - "service"
            - "postgresdb"
      containers:
      - name: crapi-identity
        image: crapi/crapi-identity:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
            - configMapRef:
                name: crapi-identity-configmap
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: 256m
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10

